### ISSUE TITLE
Which block should students use for declaring functions' prototypes?

### ISSUE THREAD

**Issue by dmalan** [cs50/harvard.cs50.droplet#13]

**Comment by dmalan** [comment]
Ideal to call it:

```
type function(parameters);
```

**Comment by dabbler0** [comment]
This required some fiddling with the parse grammar to avoid conflation between

```
long long (a);
```

being a function called "long" taking a parameter named "a" and a variable called "a" with type "long long." Because the parentheses here are superfluous in the second case, we now always take this as the first one (a function prototype).

This should be fine, but if problems in the grammar come up I'll reopen this issue.
