### ISSUE TITLE
when you drag a block away and it becomes a comment, then change to Text mode, commented block is gone

### ISSUE THREAD

**Issue by dmalan** [cs50/harvard.cs50.droplet#26]
**before:**

![blocks](https://cloud.githubusercontent.com/assets/788678/18004743/c460192e-6b63-11e6-9eb3-cfac9180d0bd.png)

**after:**

![text](https://cloud.githubusercontent.com/assets/788678/18004746/c7b7f88a-6b63-11e6-8262-8b588230b2a2.png)

**Comment by dabbler0** [comment]
This one's tricky. The "comment" thing that you get when you drag a block into space was a Code.org idea -- it's not really a comment, instead just a scratch space where you can assemble stuff in two dimensions instead of being bound to the left side of the screen.

We talked a bunch about how we might incorporate them into the program itself, and decided that because we wanted a strict bijection between text and blocks, we didn't want to include the free-floating blocks in the program because it would need some coordinate metadata, which was no good. So it's just a temporary workspace for kids to assemble blocks in weird orders if they want or view code snippets side-by-side.

Code.org recommended that we wrap them in the comment symbol to show that they wouldn't be part of the program when it ran. Not sure if that's confusing -- I think it would be more confusing not to have them, though.

**Comment by dmalan** [comment]
Just to recap in-person chat, if a user has orphaned blocks in blocks mode and tries to switch to text mode, should first be prompted to confirm with, e.g.:

> You currently have _n_ blocks that aren't connected to the rest of your code. If you switch to text mode, those blocks will disappear. Are you sure you want to switch to text mode?"

**Comment by dmalan** [comment]
Best to listen for `body.unload` and tab closing so as to prompt the user too. Or, instead of former, store disconnected blocks' state in C9 storage.

**Comment by dabbler0** [comment]
I've hooked into close and toggle, and done a prompt on `body.unload` for now. @kzidane do you know how I would add extra session data to be preserved between reloads, like c9 does with Ace editor scroll data/unsaved edits?

**Comment by kzidane** [comment]
@dabbler0 see https://cloud9-sdk.readme.io/docs/creating-an-editor-plugin#section-serializing-and-deserializing!

**Comment by dabbler0** [comment]
@kzidane Thanks!

**Comment by dabbler0** [comment]
@kzidane @dmalan Branch https://github.com/cs50/harvard.cs50.droplet/tree/floating-block-restore has a prototype for all the functionality we want, but will depend on a pull to core https://github.com/cs50/core/pull/1.

**Comment by dabbler0** [comment]
@kzidane @dmalan Update: the pull request to c9 core is https://github.com/c9/core/pull/377.

**Comment by kzidane** [comment]
@dabbler0 I might have found a way to extend the state, that doesn't require changing ace's implementation, or PRing the core. Would extending the meta object work for you?

```
var doc = tab.document;

// retrieve current state
var state = doc.getState();
state.meta.droplet = 42; // could be any value

// inform state's changed
state.changed = true; 

// update state
doc.setState(state); 
```

cc @dmalan

**Comment by dmalan** [comment]
@dabbler0 what do you think about @kzidane's proposal?

**Comment by dabbler0** [comment]
@dmalan @kzidane This should be resolved now; uses `document.meta` instead of depending on the puull to core.
