### ISSUE TITLE
space in argument treated as newline

### ISSUE THREAD

**Issue by brianyu28** [cs50/harvard.cs50.droplet#34]
When I add a space inside of an already existing argument to printf, it gets treated as a newline. 

Reproduce it as follows: create a new printf block, enter the string “foobar,” then go back and place your cursor between “foo” and “bar” and try to add a space.

<img width="208" alt="screen shot 2017-05-31 at 3 49 48 pm" src="https://cloud.githubusercontent.com/assets/16066224/26650900/ee6b70a2-4618-11e7-8296-2dc27f1f88d2.png">

**Comment by dabbler0** [comment]
This was the weirdest bug! This actually happens because of _line wrapping in the hidden textarea_. When you put a space in, the hidden textarea (which is very small) decides it's okay to wrap "bar" to the next line, since "foobar" is longer than one line. Then for some reason, and I think this is a recent browser change, this actually changes the `textarea.value` read out of it to include the newline to reflect the wrapping, as if the textarea had `wrap="hard"`.

This was fixable by adding `white-space: nowrap` to the textarea. It is fixed in Droplet as of cb35bb66abe34f9f447dee652a8c90a1c25910c1, and I'll pull the code into `harvard.cs50.droplet` soon.

**Comment by dabbler0** [comment]
Should now be fixed in `harvard.cs50.droplet` as well as of 214ffcc6dc389e8eea23291897cf8faf193ec89f.
