### ISSUE TITLE
set min/max width when resizing?

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#39]
Right now, it's possible to resize the puzzles pane so that it has less width than it needs which leads to this:

![resize](https://cloud.githubusercontent.com/assets/7230211/26658227/f884531a-4668-11e7-875e-cfaf18c6e184.png)

It's also possible to drag the divider way to the right till it goes outside of the pane, which might be frustrating for some to reset:
 
![resize](https://cloud.githubusercontent.com/assets/7230211/26658278/460998fc-4669-11e7-9820-1570889d0546.gif)

**Comment by dabbler0** [comment]
It is sometimes good to be able to shrink the palette down to nothing, for instance for display purposes or when you're mostly typing. Rather than enforce a minimum width I've given the palette element `overflow:hidden` so that the visual effect is still good.

I've enforced a maximum width of total width - gutter size, so that at least the line numbers are always visible on the right.

These should be in effect now.

**Comment by dabbler0** [comment]
This has been fixed; closing.

**Comment by kzidane** [comment]
Seems not completely fixed? 
 
![resizing](https://user-images.githubusercontent.com/7230211/27975371-d8535a6c-632f-11e7-996b-5fc191a0207f.gif)

If I touch an edge, mouse up, and move, it still resizes (as if the mouse's still down) too.

**Comment by dlloyd09** [comment]
Maybe a button that autocollapses, akin to what the native C9 file browser icon does. CC @kzidane. Still should maintain a minimum width for the palette.

**Comment by dabbler0** [comment]
Enforcing a minimum width of 200px as of 01fb4bf74056e70b7dfb313e4d3aca2e9cfcbc6b
