### ISSUE TITLE
dangling pieces will disappear

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#40]
If I have some dangling puzzle piece(s), and I switch to Text mode frequently, it might get quite annoying to keep confirming that dangling piece(s) will disappear per:

![disappear](https://cloud.githubusercontent.com/assets/7230211/26658435/65b8d69e-466a-11e7-92df-3bc1acd0c9c0.png)

Though it does disappear in Text mode, it doesn't really disappear in Blocks mode (i.e., if I switch back from Text to Blocks, it's there). Should we rephrase the message? Might adding "never ask again" checkbox, and having this setting possibly toggled back on again from preferences be of interest?

**Comment by dabbler0** [comment]
@dmalan What do you think is the best interface/wording?

**Comment by dmalan** [comment]
@dabbler0 can we add the checkbox and have it silence the alert _for that open tab_? But if user closes and reopens the file, alert can reappear until student re-checks.

**Comment by dabbler0** [comment]
This is functional now:

![2017-06-28-222544_1366x768_scrot](https://user-images.githubusercontent.com/682790/27668746-dcdc8792-5c50-11e7-92ef-4ee537475a09.png)

Note that the checkbox is on a different line from the confirm buttons, as opposed to how alerts do it. This is because the checkbox is hacked into a "confirm" dialog rather than constructing a new kind of dialog from scratch. I can change this later to be in line with other dialogs, but I don't think the difference is noticeable for the time being.

**Comment by dmalan** [comment]
@kzidane is there an easy way to tidy the checkbox to be on the same line as the confirm buttons?

**Comment by kzidane** [comment]
https://github.com/c9/core/pull/449

**Comment by kzidane** [comment]
If we don't want to wait 'til this is merged and deployed, I think it might be possible by creating and inserting [checkbox](https://apidoc.c9.io/c9v3/#!/api/ui.checkbox) and filler elements on confirmation dialog `show` event and hide it on `hide`? That way we shouldn't have to create a dialog from scratch?

**Comment by kzidane** [comment]
FYI, @dabbler0, https://github.com/c9/core/pull/449 is now merged.
