### ISSUE TITLE
typedef turns into invalid block

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#49]
![typedef](https://user-images.githubusercontent.com/7230211/27973913-c1fb3c5e-6329-11e7-8823-a8f2c6af9ed7.gif)

**Comment by dabbler0** [comment]
What is the expected behavior? I believe that this is in fact how the C parse tree works, but maybe we want to change the interface. I can think of a couple options:
  - Merge `[typedef X] A` into `[typedef X A]` (all one block) whenever we encounter this pattern
  - Merge `[[typedef [struct { }] A]]` all into one block whenever we encounter this pattern
  - Do both of the above (merge as much as possible)

**Comment by dlloyd09** [comment]
@kzidane @dmalan

**Comment by kzidane** [comment]
@dabbler0 if we have one block `[typedef X A]`, `X` can't be `struct` in this case? Point is that if we remove `X`, `A`, or both, block should stay presumably usable `typedef` block, as it's the case with other blocks. 

If `X` can't be a `struct` per the question above, I guess doing both would be ideal, unless @dmalan has other thoughts.

**Comment by dabbler0** [comment]
My question is whether we want to absorb the "struct" block into the "typedef" block or not; should we let the remove "struct" so that they can do things like `typedef long long ll`, or should we assume that the pattern is always going to include a struct? I'll work on absorbing "typedef" into the declaration, in any case.

By the way, in the C parse tree, `typedef` is the same kind of token as `static`; the expression is actually parsed like a variable/function declaration, like `typedef int *f(int, int);` forms the same tree as `static int *f(int, int)`, which is why `typedef` is being associated with `int` here.

**Comment by kzidane** [comment]
I don't think we should assume the pattern is always going to be a `struct` because technically it can be other things? It might be useful though to have a variant with a `struct` block already plugged in as `X`, since that's what students use mostly. Lets see what @dmalan thinks though!

**Comment by dmalan** [comment]
@dabbler0, instead of having this block exist:

![screen shot 2017-07-15 at 11 55 12 am](https://user-images.githubusercontent.com/788678/28240734-c61ee854-6954-11e7-99b1-adcc32fb2bfa.png)

could/should we instead just have a block like the below that accepts a type (a `struct` or primitive or other `typedef`'d type) inside of it?

![screen shot 2017-07-15 at 11 55 07 am](https://user-images.githubusercontent.com/788678/28240757-1f26c156-6955-11e7-972b-398c931b02b7.png)

Would that help address this issue?

**Comment by dlloyd09** [comment]
Seems we all concur on @dmalan 's approach

**Comment by dabbler0** [comment]
Merged typedef into the parent declaration block like so:
![2017-08-09-130835_1366x768_scrot](https://user-images.githubusercontent.com/682790/29134223-02bce9ec-7d04-11e7-9bf9-30cfbb6e6905.png)
