### ISSUE TITLE
sizeof block doesn't handle expressions

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#50]
![sizeof](https://user-images.githubusercontent.com/7230211/27974509-3b34da92-632c-11e7-8116-65f8bcd75641.gif)

**Comment by dabbler0** [comment]
My plan here is to absorb the "(" ")" parentheses into sizeof() even when the argument to `sizeof expr` is an expression. This should fix this issue as long as `sizeof()` is always used with parentheses in the

This is a little bit of a hack. Two caveats:
  - Entering a type name into a `sizeof()` with an expression inside will not cause the type dropdown to reappear (like it does in the palette). This is because the parser can't distinguish between a type name and a variable name; is `foo` a type or a variable? However, it will properly parse. Also, typing in more complex types like `long int*` will work and properly parse.
  - There is a form of sizeof `sizeof unaryExpression` that does not require parentheses. For instance, `sizeof 1` is valid. `sizeof long long` is not valid, however, and if you type `long long` into the `1` socket when there are no parentheses, it won't add the parentheses or reparse. Implementing that feature would take a longer time. This should not be an issue unless you think you will encounter this form of `sizeof`.

**Comment by dabbler0** [comment]
This is now implemented and pushed through to `harvard.cs50.droplet`, so if the behavior is satisfactory I will close.

**Comment by kzidane** [comment]
@dabbler0, sorry, is this part of #43?

**Comment by dabbler0** [comment]
@kzidane Yep! I can't write to master at the moment so everything's going into that branch.

**Comment by dmalan** [comment]
I've disabled PR requirements for `master` now, @dabbler0!

**Comment by dmalan** [comment]
@dabbler0, should this one now be closed?

**Comment by dmalan** [comment]
Actually, still seems to be an issue, @dabbler0.

**Comment by dlloyd09** [comment]
Lower priority for the moment, but let's think about how to attack this one in a different way.

**Comment by crossroads1112** [comment]
Fixed now with the caveats Anthony mentioned above.   Converting `sizeof 1`to blocks and then replacing 1 with `int` will result in code that doesn't compile since there's no way to distinguish between types and variable names.
