### ISSUE TITLE
disable cursor

### ISSUE THREAD

**Issue by dlloyd09** [cs50/harvard.cs50.droplet#58]

**Comment by dabbler0** [comment]
Cursor should be disabled now along with associated behaviors (pressing enter to type a custom block, deleting at the cursor, pasting).

Note that this means there's no way to paste into blocks mode as of right now. This might be fixed in the future when we have time to go for the Scratch-like copy-paste behavior. If we feel like we really need paste we should bring the cursor back (this is easy as I've just made it a flag).
