### ISSUE TITLE
causes "save file?" prompt to appear twice when there's floating block

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#65]
![save-file](https://user-images.githubusercontent.com/7230211/28797651-0a98e5e4-7610-11e7-9412-0eb9129fc9a4.gif)

**Comment by dabbler0** [comment]
Fixed now, but setting `tab.meta.ignoreSave` after the floating blocks confirmation. Relies on the assumption that our plugin will be loaded after the save plugin, but this seems safe as the save plugin is part of core?

**Comment by kzidane** [comment]
In production, droplet is a preinstalled plugin just like Cloud9's save. If we want to ensure droplet is loaded after save, we should specify save as dependency by listing it per `main.consumes`. Seems to be ignoring confirmation altogether now:

![save](https://user-images.githubusercontent.com/7230211/29627865-8ba35f90-8801-11e7-8fd1-ecdae272f7fc.gif)

**Comment by dabbler0** [comment]
I think I found a more stable fix that works by adding an empty element to the undo stack so that c9 thinks it has been changed (every Droplet change does a `setValue` on the ace editor, which makes c9 think that no changes have occurred since it clears the undo stack; I add an empty element so that c9 thinks there are changes).
