### ISSUE TITLE
dangling pieces are associated with editor instances rather than document?

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#80]
![dangling](https://user-images.githubusercontent.com/7230211/29996443-71da835e-8fcc-11e7-9bde-6a2f25d62771.gif)

**Comment by crossroads1112** [comment]
@kzidane this appears to have been fixed already.

**Comment by crossroads1112** [comment]
Okay so as it turns out, it was only partially fixed when I closed this. Sorry about that. It should actually be fixed now. Floating blocks are indeed associated, by necessity, with Droplet editor sessions and there are a lot of subtle corner cases here. The following changes were made to (seemingly) cover all of them:

* Whenever the canvas canvas, Droplet now saves its floating blocks in `document.state.meta.dropletState.floatingBlocks` as well as the information about the cursor in `document.state.meta.dropletState.cursor` (not saving/restoring the cursor leads to many subtle bugs as it turns out)
https://github.com/cs50/harvard.cs50.droplet/blob/048c55532fb332ac43fe8bb0fcc0b5915b636697/droplet.js#L619-L635

* Whenever the `changeSession` event is triggered on a particular ace instance, we restore whatever state we have stored about the "new" document, via this function:. https://github.com/cs50/harvard.cs50.droplet/blob/048c55532fb332ac43fe8bb0fcc0b5915b636697/droplet.js#L379-L413
